import type {
  Drone,
  GroundRobot,
  Camera,
  Alert,
  Mission,
  Detection,
  User,
  Weather,
  SystemMetrics,
} from "@/types";

// ─── Drones ───────────────────────────────────────────────────────────────────

export const mockDrones: Drone[] = [
  {
    id: "DRN-001",
    name: "Falcon Alpha",
    model: "DJI Matrice 350 RTK",
    status: "patrol",
    battery: 78,
    lat: 25.2048,
    lng: 55.2708,
    altitude: 120,
    heading: 45,
    speed: 14.5,
    flightTime: 3240,
    temperature: 42,
    windSpeed: 12,
    motors: [
      { id: "M1", rpm: 4200, temp: 58, health: 96 },
      { id: "M2", rpm: 4180, temp: 57, health: 98 },
      { id: "M3", rpm: 4210, temp: 59, health: 94 },
      { id: "M4", rpm: 4190, temp: 56, health: 97 },
    ],
    obstacleDistance: 85,
    lidarStatus: "active",
    missionStatus: "SECTOR-7 PATROL",
    connectionQuality: 92,
    satellites: 18,
    signalStrength: 88,
    storageUsed: 64,
    storageTotal: 256,
    firmware: "v4.1.20",
    lastSeen: new Date(),
    assignedMission: "MSN-001",
  },
  {
    id: "DRN-002",
    name: "Raptor Bravo",
    model: "Autel EVO Max 4T",
    status: "online",
    battery: 95,
    lat: 25.2148,
    lng: 55.2808,
    altitude: 80,
    heading: 180,
    speed: 0,
    flightTime: 1800,
    temperature: 38,
    windSpeed: 10,
    motors: [
      { id: "M1", rpm: 0, temp: 35, health: 99 },
      { id: "M2", rpm: 0, temp: 34, health: 99 },
      { id: "M3", rpm: 0, temp: 36, health: 98 },
      { id: "M4", rpm: 0, temp: 35, health: 100 },
    ],
    obstacleDistance: 120,
    lidarStatus: "active",
    missionStatus: "STANDBY",
    connectionQuality: 98,
    satellites: 22,
    signalStrength: 95,
    storageUsed: 12,
    storageTotal: 256,
    firmware: "v3.2.11",
    lastSeen: new Date(),
  },
  {
    id: "DRN-003",
    name: "Shadow Charlie",
    model: "Skydio X10",
    status: "returning",
    battery: 23,
    lat: 25.1948,
    lng: 55.2608,
    altitude: 60,
    heading: 270,
    speed: 18,
    flightTime: 5400,
    temperature: 55,
    windSpeed: 15,
    motors: [
      { id: "M1", rpm: 3800, temp: 68, health: 88 },
      { id: "M2", rpm: 3820, temp: 70, health: 85 },
      { id: "M3", rpm: 3790, temp: 67, health: 90 },
      { id: "M4", rpm: 3810, temp: 69, health: 87 },
    ],
    obstacleDistance: 45,
    lidarStatus: "active",
    missionStatus: "RTH - LOW BATTERY",
    connectionQuality: 76,
    satellites: 15,
    signalStrength: 72,
    storageUsed: 180,
    storageTotal: 256,
    firmware: "v2.8.5",
    lastSeen: new Date(),
    assignedMission: "MSN-002",
  },
  {
    id: "DRN-004",
    name: "Viper Delta",
    model: "Parrot Anafi USA",
    status: "charging",
    battery: 45,
    lat: 25.2248,
    lng: 55.2908,
    altitude: 0,
    heading: 0,
    speed: 0,
    flightTime: 0,
    temperature: 28,
    windSpeed: 8,
    motors: [
      { id: "M1", rpm: 0, temp: 28, health: 95 },
      { id: "M2", rpm: 0, temp: 28, health: 96 },
      { id: "M3", rpm: 0, temp: 29, health: 94 },
      { id: "M4", rpm: 0, temp: 28, health: 97 },
    ],
    obstacleDistance: 0,
    lidarStatus: "inactive",
    missionStatus: "CHARGING",
    connectionQuality: 100,
    satellites: 0,
    signalStrength: 100,
    storageUsed: 96,
    storageTotal: 256,
    firmware: "v5.0.2",
    lastSeen: new Date(),
  },
  {
    id: "DRN-005",
    name: "Eagle Echo",
    model: "DJI Mavic 3 Enterprise",
    status: "emergency",
    battery: 8,
    lat: 25.1848,
    lng: 55.2508,
    altitude: 35,
    heading: 90,
    speed: 22,
    flightTime: 6720,
    temperature: 68,
    windSpeed: 22,
    motors: [
      { id: "M1", rpm: 4500, temp: 85, health: 65 },
      { id: "M2", rpm: 4480, temp: 88, health: 62 },
      { id: "M3", rpm: 4510, temp: 84, health: 68 },
      { id: "M4", rpm: 4490, temp: 87, health: 60 },
    ],
    obstacleDistance: 15,
    lidarStatus: "error",
    missionStatus: "EMERGENCY LAND",
    connectionQuality: 45,
    satellites: 12,
    signalStrength: 42,
    storageUsed: 240,
    storageTotal: 256,
    firmware: "v4.1.20",
    lastSeen: new Date(),
    assignedMission: "MSN-003",
  },
  {
    id: "DRN-006",
    name: "Hawk Foxtrot",
    model: "Quantum Systems Vector",
    status: "offline",
    battery: 0,
    lat: 25.2348,
    lng: 55.3008,
    altitude: 0,
    heading: 0,
    speed: 0,
    flightTime: 0,
    temperature: 24,
    windSpeed: 0,
    motors: [
      { id: "M1", rpm: 0, temp: 24, health: 100 },
      { id: "M2", rpm: 0, temp: 24, health: 100 },
      { id: "M3", rpm: 0, temp: 24, health: 100 },
      { id: "M4", rpm: 0, temp: 24, health: 100 },
    ],
    obstacleDistance: 0,
    lidarStatus: "inactive",
    missionStatus: "OFFLINE",
    connectionQuality: 0,
    satellites: 0,
    signalStrength: 0,
    storageUsed: 0,
    storageTotal: 256,
    firmware: "v1.5.8",
    lastSeen: new Date(Date.now() - 3600000),
  },
];

// ─── Ground Robots ────────────────────────────────────────────────────────────

export const mockRobots: GroundRobot[] = [
  {
    id: "RBT-001",
    name: "Sentinel Prime",
    model: "Boston Dynamics Spot",
    status: "patrol",
    battery: 82,
    lat: 25.2058,
    lng: 55.2718,
    heading: 120,
    speed: 1.8,
    motorHealth: 97,
    wheelSpeed: [1.8, 1.8, 1.9, 1.7],
    lidarStatus: "active",
    obstacleDetected: false,
    autonomousMode: true,
    connectionQuality: 94,
    lastSeen: new Date(),
    assignedMission: "MSN-001",
  },
  {
    id: "RBT-002",
    name: "Guardian Rex",
    model: "Clearpath Husky",
    status: "idle",
    battery: 67,
    lat: 25.2158,
    lng: 55.2818,
    heading: 0,
    speed: 0,
    motorHealth: 91,
    wheelSpeed: [0, 0, 0, 0],
    lidarStatus: "active",
    obstacleDetected: false,
    autonomousMode: false,
    connectionQuality: 88,
    lastSeen: new Date(),
  },
  {
    id: "RBT-003",
    name: "Titan Gamma",
    model: "ANYbotics ANYmal",
    status: "charging",
    battery: 34,
    lat: 25.1958,
    lng: 55.2618,
    heading: 0,
    speed: 0,
    motorHealth: 89,
    wheelSpeed: [0, 0, 0, 0],
    lidarStatus: "inactive",
    obstacleDetected: false,
    autonomousMode: false,
    connectionQuality: 100,
    lastSeen: new Date(),
  },
];

// ─── Cameras ──────────────────────────────────────────────────────────────────

export const mockCameras: Camera[] = [
  { id: "CAM-001", name: "Gate Alpha PTZ", type: "ptz", status: "recording", lat: 25.2068, lng: 55.2728, resolution: "4K", fps: 30, recording: true, bandwidth: 12, storageUsed: 480, lastSeen: new Date() },
  { id: "CAM-002", name: "Perimeter North", type: "cctv", status: "online", lat: 25.2168, lng: 55.2828, resolution: "1080p", fps: 25, recording: true, bandwidth: 6, storageUsed: 240, lastSeen: new Date() },
  { id: "CAM-003", name: "Thermal Zone A", type: "thermal", status: "recording", lat: 25.1968, lng: 55.2628, resolution: "640x512", fps: 30, recording: true, bandwidth: 8, storageUsed: 320, lastSeen: new Date() },
  { id: "CAM-004", name: "IR Sector 5", type: "ir", status: "online", lat: 25.2268, lng: 55.2928, resolution: "1080p", fps: 25, recording: false, bandwidth: 5, storageUsed: 160, lastSeen: new Date() },
  { id: "CAM-005", name: "RTSP Entrance B", type: "rtsp", status: "error", lat: 25.1868, lng: 55.2528, resolution: "4K", fps: 0, recording: false, bandwidth: 0, storageUsed: 96, lastSeen: new Date(Date.now() - 1800000) },
  { id: "CAM-006", name: "Gate Bravo PTZ", type: "ptz", status: "recording", lat: 25.2368, lng: 55.3028, resolution: "4K", fps: 30, recording: true, bandwidth: 14, storageUsed: 560, lastSeen: new Date() },
  { id: "CAM-007", name: "Thermal Zone B", type: "thermal", status: "online", lat: 25.2468, lng: 55.3128, resolution: "640x512", fps: 30, recording: true, bandwidth: 8, storageUsed: 280, lastSeen: new Date() },
  { id: "CAM-008", name: "Perimeter South", type: "cctv", status: "offline", lat: 25.1768, lng: 55.2428, resolution: "1080p", fps: 0, recording: false, bandwidth: 0, storageUsed: 120, lastSeen: new Date(Date.now() - 7200000) },
];

// ─── Alerts ───────────────────────────────────────────────────────────────────

export const mockAlerts: Alert[] = [
  {
    id: "ALT-001",
    type: "intrusion",
    priority: "critical",
    title: "Unauthorized Perimeter Breach",
    description: "AI detected unauthorized individual crossing restricted zone boundary at Gate Alpha.",
    lat: 25.2068,
    lng: 55.2728,
    location: "Gate Alpha - Sector 7",
    timestamp: new Date(Date.now() - 120000),
    confidence: 97.3,
    acknowledged: false,
    sourceDevice: "CAM-001",
    aiAnalysis: "Individual detected moving at high speed through restricted zone. Carrying unidentified object. No authorized personnel ID match found.",
    suggestedResponse: "Deploy Drone DRN-001 for visual confirmation. Alert security team at Gate Alpha. Lock down adjacent sectors.",
  },
  {
    id: "ALT-002",
    type: "weapon",
    priority: "critical",
    title: "Weapon Detected",
    description: "YOLOv11 model identified possible firearm in Frame 4082 captured by thermal camera.",
    lat: 25.1968,
    lng: 55.2628,
    location: "Thermal Zone A - Building C",
    timestamp: new Date(Date.now() - 300000),
    confidence: 91.8,
    acknowledged: false,
    sourceDevice: "CAM-003",
    aiAnalysis: "Object classified as handgun with 91.8% confidence. Subject appears to be concealing object under clothing. Gait analysis indicates stress behavior.",
    suggestedResponse: "Immediate security response required. Notify law enforcement. Track subject with DRN-003.",
  },
  {
    id: "ALT-003",
    type: "fire",
    priority: "high",
    title: "Fire / Smoke Detected",
    description: "Thermal anomaly and smoke signature detected in warehouse area.",
    lat: 25.2148,
    lng: 55.2808,
    location: "Warehouse District - Block 3",
    timestamp: new Date(Date.now() - 600000),
    confidence: 88.5,
    acknowledged: true,
    assignedTo: "OPR-002",
    sourceDevice: "CAM-002",
    aiAnalysis: "Temperature anomaly: 340°C. Smoke density increasing. Wind direction: NW at 12 knots. Adjacent structures at risk.",
    suggestedResponse: "Alert fire suppression team. Evacuate personnel within 200m radius. Deploy DRN-002 for aerial assessment.",
  },
  {
    id: "ALT-004",
    type: "loitering",
    priority: "medium",
    title: "Suspicious Loitering",
    description: "Individual detected lingering near critical infrastructure for over 15 minutes.",
    lat: 25.2248,
    lng: 55.2908,
    location: "Power Station - Access Road",
    timestamp: new Date(Date.now() - 900000),
    confidence: 85.2,
    acknowledged: false,
    sourceDevice: "CAM-006",
    aiAnalysis: "Same individual has remained stationary for 17 minutes. Multiple attempts to approach access door. No valid credentials detected.",
    suggestedResponse: "Send security officer for ID check. Monitor with PTZ camera. Document activity.",
  },
  {
    id: "ALT-005",
    type: "vehicle",
    priority: "medium",
    title: "Unauthorized Vehicle Detected",
    description: "Unregistered vehicle entered restricted parking area.",
    lat: 25.1848,
    lng: 55.2508,
    location: "Restricted Lot B",
    timestamp: new Date(Date.now() - 1800000),
    confidence: 94.1,
    acknowledged: true,
    assignedTo: "OPR-001",
    sourceDevice: "CAM-004",
    aiAnalysis: "License plate: unregistered in system. Vehicle: dark SUV. Occupants: 2 detected. Vehicle stationary for 8 minutes.",
    suggestedResponse: "Dispatch ground unit for plate verification. Log vehicle details.",
  },
  {
    id: "ALT-006",
    type: "fence_crossing",
    priority: "high",
    title: "Fence Breach Detected",
    description: "Multiple individuals detected crossing perimeter fence at north sector.",
    lat: 25.2468,
    lng: 55.3128,
    location: "North Perimeter - Sector 12",
    timestamp: new Date(Date.now() - 450000),
    confidence: 96.7,
    acknowledged: false,
    sourceDevice: "CAM-007",
    aiAnalysis: "Three individuals detected breaching perimeter fence. Movement is coordinated suggesting planned entry. Night-vision confirms tactical clothing.",
    suggestedResponse: "URGENT: Deploy rapid response team. Activate perimeter lighting. Track with DRN-001.",
  },
];

// ─── Missions ─────────────────────────────────────────────────────────────────

export const mockMissions: Mission[] = [
  {
    id: "MSN-001",
    name: "Operation Night Watch",
    type: "patrol",
    status: "active",
    priority: "high",
    assignedDrones: ["DRN-001"],
    assignedRobots: ["RBT-001"],
    waypoints: [
      { id: "WP-1", lat: 25.2048, lng: 55.2708, altitude: 100, speed: 15, hoverTime: 30, action: "scan" },
      { id: "WP-2", lat: 25.2148, lng: 55.2808, altitude: 100, speed: 15, hoverTime: 30, action: "scan" },
      { id: "WP-3", lat: 25.1948, lng: 55.2608, altitude: 100, speed: 15, hoverTime: 60, action: "thermal_scan" },
    ],
    startTime: new Date(Date.now() - 5400000),
    progress: 65,
    description: "Automated night patrol covering sectors 1-8 with AI threat detection enabled.",
    operatorId: "USR-001",
    geofence: [[25.18, 55.25], [25.25, 55.25], [25.25, 55.32], [25.18, 55.32]],
  },
  {
    id: "MSN-002",
    name: "Perimeter Survey Alpha",
    type: "surveillance",
    status: "active",
    priority: "medium",
    assignedDrones: ["DRN-003"],
    assignedRobots: [],
    waypoints: [
      { id: "WP-1", lat: 25.1948, lng: 55.2608, altitude: 80, speed: 10, hoverTime: 120, action: "record" },
      { id: "WP-2", lat: 25.2048, lng: 55.2708, altitude: 80, speed: 10, hoverTime: 60, action: "record" },
    ],
    startTime: new Date(Date.now() - 3600000),
    progress: 80,
    description: "Full perimeter surveillance with 4K recording and license plate recognition.",
    operatorId: "USR-002",
  },
  {
    id: "MSN-003",
    name: "Emergency Response Alpha",
    type: "response",
    status: "active",
    priority: "critical",
    assignedDrones: ["DRN-005"],
    assignedRobots: [],
    waypoints: [
      { id: "WP-1", lat: 25.1848, lng: 55.2508, altitude: 35, speed: 22, hoverTime: 0, action: "emergency" },
    ],
    startTime: new Date(Date.now() - 600000),
    progress: 30,
    description: "Emergency response to intrusion alert at north perimeter. DRN-005 on intercept path.",
    operatorId: "USR-001",
  },
  {
    id: "MSN-004",
    name: "Facility Inspection Bravo",
    type: "inspection",
    status: "planned",
    priority: "low",
    assignedDrones: ["DRN-002"],
    assignedRobots: ["RBT-002"],
    waypoints: [
      { id: "WP-1", lat: 25.2248, lng: 55.2908, altitude: 50, speed: 8, hoverTime: 60, action: "inspect" },
      { id: "WP-2", lat: 25.2348, lng: 55.3008, altitude: 50, speed: 8, hoverTime: 60, action: "inspect" },
    ],
    scheduledTime: new Date(Date.now() + 7200000),
    progress: 0,
    description: "Scheduled facility inspection covering solar panels, rooftops, and exterior walls.",
    operatorId: "USR-003",
  },
];

// ─── Detections ───────────────────────────────────────────────────────────────

export const mockDetections: Detection[] = [
  { id: "DET-001", class: "person", confidence: 97.3, bbox: { x: 120, y: 80, width: 60, height: 140 }, timestamp: new Date(Date.now() - 30000), lat: 25.2068, lng: 55.2728, sourceDevice: "CAM-001", priority: "critical", tracked: true },
  { id: "DET-002", class: "vehicle", confidence: 94.1, bbox: { x: 200, y: 150, width: 180, height: 100 }, timestamp: new Date(Date.now() - 60000), lat: 25.1848, lng: 55.2508, sourceDevice: "CAM-004", priority: "medium", tracked: true, licensePlate: "UNK-4829" },
  { id: "DET-003", class: "weapon", confidence: 91.8, bbox: { x: 300, y: 200, width: 45, height: 20 }, timestamp: new Date(Date.now() - 180000), lat: 25.1968, lng: 55.2628, sourceDevice: "CAM-003", priority: "critical", tracked: false },
  { id: "DET-004", class: "fire", confidence: 88.5, bbox: { x: 400, y: 100, width: 120, height: 90 }, timestamp: new Date(Date.now() - 300000), lat: 25.2148, lng: 55.2808, sourceDevice: "CAM-002", priority: "high", tracked: false },
  { id: "DET-005", class: "crowd", confidence: 85.2, bbox: { x: 50, y: 250, width: 400, height: 200 }, timestamp: new Date(Date.now() - 450000), lat: 25.2268, lng: 55.2928, sourceDevice: "CAM-006", priority: "medium", tracked: true },
  { id: "DET-006", class: "license_plate", confidence: 99.1, bbox: { x: 220, y: 180, width: 80, height: 30 }, timestamp: new Date(Date.now() - 600000), lat: 25.1848, lng: 55.2508, sourceDevice: "CAM-004", priority: "low", tracked: false, licensePlate: "AXZ-7741" },
];

// ─── Users ────────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  { id: "USR-001", name: "Col. Marcus Webb", email: "m.webb@sentinel-x.mil", role: "commander", online: true, lastActive: new Date(), assignedMissions: ["MSN-001", "MSN-003"], permissions: ["*"] },
  { id: "USR-002", name: "Lt. Sarah Chen", email: "s.chen@sentinel-x.mil", role: "operator", online: true, lastActive: new Date(), assignedMissions: ["MSN-002"], permissions: ["drones.read", "drones.control", "missions.read"] },
  { id: "USR-003", name: "Sgt. Omar Hassan", email: "o.hassan@sentinel-x.mil", role: "drone_pilot", online: false, lastActive: new Date(Date.now() - 1800000), assignedMissions: ["MSN-004"], permissions: ["drones.read", "drones.control"] },
  { id: "USR-004", name: "Dr. Elena Vasquez", email: "e.vasquez@sentinel-x.mil", role: "security_analyst", online: true, lastActive: new Date(), assignedMissions: [], permissions: ["analytics.read", "alerts.read"] },
  { id: "USR-005", name: "Admin Root", email: "admin@sentinel-x.mil", role: "super_admin", online: true, lastActive: new Date(), assignedMissions: [], permissions: ["*"] },
];

// ─── Weather ──────────────────────────────────────────────────────────────────

export const mockWeather: Weather = {
  temp: 34,
  feelsLike: 38,
  humidity: 62,
  windSpeed: 14,
  windDirection: 225,
  visibility: 12,
  condition: "Partly Cloudy",
  icon: "cloud-sun",
  pressure: 1013,
  uvIndex: 7,
  forecast: [
    { hour: "18:00", temp: 32, windSpeed: 12, condition: "Cloudy" },
    { hour: "21:00", temp: 28, windSpeed: 10, condition: "Clear" },
    { hour: "00:00", temp: 24, windSpeed: 8, condition: "Clear" },
    { hour: "03:00", temp: 22, windSpeed: 7, condition: "Clear" },
    { hour: "06:00", temp: 21, windSpeed: 9, condition: "Partly Cloudy" },
    { hour: "09:00", temp: 26, windSpeed: 11, condition: "Sunny" },
  ],
};

// ─── System Metrics ───────────────────────────────────────────────────────────

export const mockSystemMetrics: SystemMetrics = {
  cpuUsage: 68,
  ramUsage: 74,
  gpuUsage: 82,
  networkIn: 245,
  networkOut: 88,
  storageUsed: 4.2,
  storageTotal: 20,
  activeStreams: 12,
  bandwidth: 480,
  uptime: 2592000,
};

// ─── Chart Data Generators ────────────────────────────────────────────────────

export function generateTimeSeriesData(
  points: number,
  min: number,
  max: number,
  label: string
): { time: string; value: number }[] {
  return Array.from({ length: points }, (_, i) => ({
    time: `${String(i).padStart(2, "0")}:00`,
    value: Math.floor(Math.random() * (max - min) + min),
    label,
  }));
}

export const droneActivityData = Array.from({ length: 24 }, (_, i) => ({
  hour: `${String(i).padStart(2, "0")}:00`,
  active: Math.floor(Math.random() * 5 + 1),
  missions: Math.floor(Math.random() * 4),
  detections: Math.floor(Math.random() * 20),
}));

export const threatLevelData = [
  { name: "Critical", value: 8, color: "#FF3B30" },
  { name: "High", value: 15, color: "#F59E0B" },
  { name: "Medium", value: 32, color: "#00E5FF" },
  { name: "Low", value: 45, color: "#00E676" },
];

export const detectionAccuracyData = [
  { class: "Person", accuracy: 97.3, detections: 1245 },
  { class: "Vehicle", accuracy: 96.1, detections: 876 },
  { class: "Weapon", accuracy: 91.8, detections: 23 },
  { class: "Fire", accuracy: 88.5, detections: 12 },
  { class: "Smoke", accuracy: 85.2, detections: 34 },
  { class: "License Plate", accuracy: 99.1, detections: 654 },
  { class: "Crowd", accuracy: 94.7, detections: 187 },
];
